# Site settings
# These are used to personalize your new site.
title: Lucas Neidlinger # your name here
logo: "/images/profPhoto.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer-Science (class of 2022)
  <br /><br />
  <a href="pdf/Resume2021.pdf">View My Resume</a>
  <br /><br />
  <a href="https://www.linkedin.com/in/lucas-neidlinger/">View My LinkedIn Profile</a>
repository: "neidlinger/neidlinger.github.io"
github_username:  neidlinger # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

